# Generated by Django 4.2.1 on 2023-06-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendeedata',
            options={'verbose_name': 'Attendee Data', 'verbose_name_plural': 'Attendee Data'},
        ),
        migrations.RenameField(
            model_name='attendeedata',
            old_name='type',
            new_name='event_template',
        ),
    ]
