# Generated by Django 4.2.1 on 2023-06-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_alter_attendeedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeedata',
            name='value_character',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attendeedata',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendeedata',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
