# Generated by Django 4.2.1 on 2023-06-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTempate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='event.event')),
            ],
        ),
    ]
