# Generated by Django 4.2.1 on 2023-06-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtempate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'verbose_name': 'Event Data', 'verbose_name_plural': 'Event Data'},
        ),
    ]
