# Generated by Django 4.2.1 on 2023-06-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='value_character',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='value_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
