# Generated by Django 4.2.1 on 2023-06-05 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventdata_value_character_eventdata_value_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='event',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
