# Generated by Django 4.2.1 on 2023-06-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='type',
            field=models.IntegerField(choices=[(1, 'Event Name'), (2, 'Event Start Date'), (3, 'Event End Date'), (4, 'Event Application Start Date'), (5, 'Event Application End Date')]),
        ),
    ]
