# Generated by Django 4.2.1 on 2023-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventdata_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtempate',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
